ccflags-y += -Idrivers/media/platform/msm/camera_v2_eagle
ccflags-y += -Idrivers/media/platform/msm/camera_v2_eagle/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_eagle/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
