ccflags-y += -Idrivers/media/platform/msm/camera_v2_eagle
ccflags-y += -Idrivers/media/platform/msm/camera_v2_eagle/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_eagle/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
